### ISSUE TITLE
Executable bit missed on bindir/* in v1.21.0

### ISSUE THREAD

**Issue by evgkrsk** [spyophobia/shadowsocks-rust-spec#2]
21f7a4fa7a5992b177729b4ceb5673deae159be0 breaks v1.21.0 release: service cannot be started after rpm upgraging because binaries miss executable bit on them.

Please revert back from 644 to 755 permissions to _bindir/*

**Comment by spyophobia** [comment]
Yep sorry just realised today. Fixed in a162b7a.
